# Общие настройки
# socks-port: 7777   # SOCKS5 proxy port (если нужен прямой доступ к SOCKS5 прокси)
listeners:
  - name: tproxy
    type: tproxy
    port: 4000 # не менять, это порт для Xkeen
allow-lan: true
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090' # адрес веб админки: http://192.168.1.1:9090/ui
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/releases/latest/download/compressed-dist.tgz"
# external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
# нужный интерфейс панели администрирования выберите сами, сейчас стоит MetaCubeX, но можно использовать и Zashboard.
# Если вы хотите использовать Zashboard, то раскомментируйте строку выше с Zashboard
# и закомментируйте строку с MetaCubeX

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
    TLS:
      ports:
      - 443
      - 8443

# --- ВАШИ ПРОКСИ-СЕРВЕРЫ ---
proxy-providers:
  sub:
    type: http
    url: https://ссылкаподписки # Вот сюда вставьте свою ссылку подписки на прокси (ВПН)
    patch: ./proxy_providers/base64.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      tfo: true
      mptcp: true
      udp: true

# --- ГРУППЫ ПРОКСИ (ПОЛИТИКИ) ---
proxy-groups:
  - name: MIHOMO
    type: select
    use:
      - sub

# --- ПОДПИСКИ НА ПРАВИЛА МАРШРУТИЗАЦИИ ---
rule-providers:
  discord_domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/discord.mrs
    path: ./rule-sets/discord_domains.mrs
    interval: 86400
  discord_voiceips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/discord-voice-ip-list.mrs
    path: ./rule-sets/discord_voiceips.mrs
    interval: 86400
  refilter_domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./re-filter/domain-rule.mrs
    interval: 86400
  refilter_ipsum:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/ip-rule.mrs
    path: ./re-filter/ip-rule.mrs
    interval: 86400
  oisd_big:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/oisd/big.mrs
    path: ./oisd/big.mrs
    interval: 86400
  torrent-trackers:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-trackers.mrs
    path: ./rule-sets/torrent-trackers.mrs
    interval: 86400
  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-clients.yaml
    path: ./rule-sets/torrent-clients.yaml
    interval: 86400
  ru-bundle:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/ru-bundle/rule.mrs
    path: ./ru-bundle/rule.mrs
    interval: 86400

# --- ПРАВИЛА МАРШРУТИЗАЦИИ ---
rules:
  - OR,((DOMAIN,ipwho.is),(DOMAIN,api.ip.sb),(DOMAIN,ipapi.co),(DOMAIN,ipinfo.io)),MIHOMO
  - RULE-SET,oisd_big,REJECT # OISD Big - блокирует рекламу
  # - DOMAIN-SUFFIX,google.com,MIHOMO # пример правила для домена google.com и всех поддоменов
  - OR,((RULE-SET,torrent-clients),(RULE-SET,torrent-trackers)),DIRECT
  - OR,((RULE-SET,discord_domains),(RULE-SET,discord_voiceips)),MIHOMO
  - RULE-SET,ru-bundle,MIHOMO
  - RULE-SET,refilter_domains,MIHOMO
  - RULE-SET,refilter_ipsum,MIHOMO
  - MATCH,DIRECT # это самая нижная строка правил, ниже ее ничего не должно быть
  # ссылка на русскоязычную документацию по правилам маршрутизации: 
  # https://wiki.metacubex.one/ru/config/