tproxy-port: 4000
allow-lan: true
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090' # адрес веб админки: http://192.168.1.1:9090/ui
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  sniff:
    HTTP:
    TLS:
    QUIC:

# --- ВАШИ ПРОКСИ-СЕРВЕРЫ ---
proxy-providers:
  sub:
    type: http
    url: https://ссылкаподписки # Замените на свою ссылку подписки на прокси (ВПН)
    path: ./proxy_providers/base64.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
      timeout: 5000
      lazy: true
      expected-status: 204
    override:
      tfo: true
      mptcp: true
      udp: true

# --- ГРУППЫ ПРОКСИ (ПОЛИТИКИ) ---
proxy-groups:
  - name: VPN
    type: select
    include-all: true
    
  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    proxies:
      - VPN
      - DIRECT
      
  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    proxies:
      - VPN
      - DIRECT

# --- ПОДПИСКИ НА ПРАВИЛА МАРШРУТИЗАЦИИ ---
rule-providers:
  telegram-domain:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/telegram.yaml
    path: ./rule-sets/telegram-domain.yaml
    interval: 86400
  telegram-ips:
    type: http
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/telegram.yaml
    path: ./rule-sets/telegram-ips.yaml
    interval: 86400
  cloudflare-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cloudflare.mrs
    path: ./rule-sets/cloudflare-domains.mrs
    interval: 86400
  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs
    path: ./rule-sets/cloudflare-ips.mrs
    interval: 86400
  discord_domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/discord.mrs
    path: ./rule-sets/discord_domains.mrs
    interval: 86400
  discord_voiceips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/discord-voice-ip-list.mrs
    path: ./rule-sets/discord_voiceips.mrs
    interval: 86400
  refilter_domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./re-filter/domain-rule.mrs
    interval: 86400
  refilter_ipsum:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/ip-rule.mrs
    path: ./re-filter/ip-rule.mrs
    interval: 86400
  oisd_big:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/oisd/big.mrs
    path: ./oisd/big.mrs
    interval: 86400
  torrent-trackers:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-trackers.mrs
    path: ./rule-sets/torrent-trackers.mrs
    interval: 86400
  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-clients.yaml
    path: ./rule-sets/torrent-clients.yaml
    interval: 86400
  ru-bundle:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/ru-bundle/rule.mrs
    path: ./ru-bundle/rule.mrs
    interval: 86400

# --- ПРАВИЛА МАРШРУТИЗАЦИИ ---
rules:
  - OR,((DOMAIN,ipwho.is),(DOMAIN,api.ip.sb),(DOMAIN,ipapi.co),(DOMAIN,ipinfo.io)),VPN
  - OR,((RULE-SET,telegram-domain),(RULE-SET,telegram-ips)),Telegram
  - OR,((RULE-SET,cloudflare-domains),(RULE-SET,cloudflare-ips)),Cloudflare
  - RULE-SET,oisd_big,REJECT # OISD Big - блокирует рекламу
  # - DOMAIN-SUFFIX,google.com,VPN # пример правила для домена google.com и всех поддоменов
  # - IP-CIDR,176.222.191.0/24,VPN,no-resolve # пример правила для IP подсети
  - OR,((RULE-SET,torrent-clients),(RULE-SET,torrent-trackers)),DIRECT
  - OR,((RULE-SET,discord_domains),(RULE-SET,discord_voiceips)),VPN
  - RULE-SET,ru-bundle,VPN
  - RULE-SET,refilter_domains,VPN
  - RULE-SET,refilter_ipsum,VPN
  - MATCH,DIRECT # это самая нижная строка правил, ниже ее ничего не должно быть
  # ссылка на русскоязычную документацию по правилам маршрутизации: 
  # https://wiki.metacubex.one/ru/config/
